### PR TITLE
[pt-BR] Update i18n

### PR DESCRIPTION
**Pull request by tetify**
I'm new to PRs, but I want to continue with the translation into Brazilian Portuguese, since the old maintainer isn't updating it anymore (for now), I want to continue with the translation of this language.

### CODE REVIEW

**Comment by kawapure** [comment]
> Erro do rehike: Falha ao encontrar o algoritmo de desencriptação.

"Rehike" is a proper noun. Shouldn't it be:

> Erro do Rehike: Falha ao encontrar o algoritmo de desencriptação.

**Comment by tetify** [comment]
i will fix this.
for now im very busy and i will see the archives of the Brazilian version of YouTube [here](https://web.archive.org/web/*/http://www.youtube.com/?gl=BR&hl=pt) and see if i can make more accurate (ex: the upload button).
i will be back later

**Comment by tetify** [comment]
#599 should fix the Rehike name in player decryption an an mini change to accuracy

**Comment by kwan-vini** [comment]
> I'm new to PRs, but I want to continue with the translation into Brazilian Portuguese, since the old maintainer isn't updating it anymore (for now), I want to continue with the translation of this language.

I am so grateful for having someone fix up and mantain my mess of a translation, since i did basically abandon Rehike and moved to V3 (though i might probably go back, if some of my expectations got realized with all the updates while i was out). Thank you so much.

**Comment by tetify** [comment]
your wellcome

**Pull request merged**
