### PR TITLE
Channel switcher page

### PR DESCRIPTION
**Pull request by syndiate**
Hey Taniko. It feels unreal to be working on a YouTube-related project again. I only decided to contribute to this project because I've been using Rehike recently and have been enjoying it. For now though, I'm just going to make rather small contributions, mostly porting pages that I programmed in my original extension (i.e. /channel_switcher and /create_channel) to this project.

This contribution is self-explanatory. There are a couple things I have to say about this though. One, the video count subtitle for each channel is not present, as a separate request needs to be done for that. I've left a comment for what to request in the ChannelSwitcherModel.php file for reference. Two, if you're logged in to multiple accounts, it will always show the channels on the first account, as the "X-Goog-Authuser" header is not sent in the InnerTube request. I'll leave it to you guys to do that, I don't really feel like reading all of Rehike's source code right now.

### CODE REVIEW

**Comment by aubymori** [comment]
> Two, if you're logged in to multiple accounts, it will always show the channels on the first account, as the "X-Goog-Auth user" header is not sent in the InnerTube request.

Yeah, there's no multiaccount support in Rehike. It'll probably be added once signin is rewritten.

**Comment by syndiate** [comment]
When will this pull req. be merged? Once multiaccount support is added?

**Comment by aubymori** [comment]
> When will this pull req. be merged? Once multiaccount support is added?

Sorry for the late response, I was in bed when I got the notification, and forgot when I got up. I just need to test it real quick, which should take only a few minutes.

**Comment by aubymori** [comment]
Looks good. Will merge now.

**Pull request merged**
