### PR TITLE
Implement 2020 and 2022 player, WIP, experimental option

### PR DESCRIPTION
**Pull request by DavidCGranger**
Sorry for being an asshole
Still WIP, needed to disable content checks, also still the requirement to disable the player cache, and slightly unstable right now. Code not pretty

### CODE REVIEW

**Comment by YukisCoffee** [comment]
Sorry for the delayed response. I am currently working on a major update (not to the player, but I haven't taken the time to review your code). I will get around to that soon enough, I hope.

**Comment by DavidCGranger** [comment]
Since you made a few changes to player in recent commits, do I need to change any of my code? I haven't gotten to looking into your changes yet, I just saw that you added some switch between a modded player (?) and a normal (?) one.

**Comment by YukisCoffee** [comment]
We had to modify Hitchhiker JS to be compatible with the latest player in dc59150, which shouldn't have any side effects, but we added a JavaScript (client-side) configuration parameter `REHIKE_LATEST_PLAYER` which is set to true in [`template/hitchhiker/core/yt_global_js_config.twig`](https://github.com/Rehike/Rehike/commit/dc59150c24cc66f340a8ccbcdfd7dd682f8035bd#diff-e7060bbf86f64015e5c685f3d7a1ba03a2840951120f93a14f2879cb0049690f). Please feel free to modify it in case it is necessary.

But I think what you're thinking is a CSS fix we added in ac6e082, which was introduced due to user complaints about the current player revision being unusable at small window sizes with the stock player sizing. We added a configuration option to toggle this CSS option. Of course, it isn't necessary with older player versions and may even conflict with other versions, so feel free to affect its behavior.

Currently, we don't have a way to handle conflicting settings, so supporting this case will require some (hopefully temporary) extra work across the codebase.

**Comment by DavidCGranger** [comment]
Thanks. I'll look into it on the weekend. Sorry for the late reply

**Comment by YukisCoffee** [comment]
Coming back to this - it will probably be implemented in the coming updates. I will take control of the changes made and expand them.

**Pull request merged**
