### PR TITLE
General player improvements

### PR DESCRIPTION
**Pull request by TorutheRedFox**
fixes rare bug reported by k/wan

also addresses #484

### CODE REVIEW

**Comment by TorutheRedFox** [comment]
image
it still has a few minor issues but that's better than literally not working at all

**Comment by TorutheRedFox** [comment]
renamed the pr again because the scope is expanding a bit

**Comment by TorutheRedFox** [comment]
now addresses #483

**Comment by TorutheRedFox** [comment]
image

**Comment by YukisCoffee** [comment]
I'm going to merge this PR, so please open a new one for additional changes.

**Pull request merged**
